//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracProje.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DboAracProjeEntities : DbContext
    {
        public DboAracProjeEntities()
            : base("name=DboAracProjeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ADMIN> TBL_ADMIN { get; set; }
        public virtual DbSet<TBL_AKMMERKEZLERI> TBL_AKMMERKEZLERI { get; set; }
        public virtual DbSet<TBL_BANKABILGI> TBL_BANKABILGI { get; set; }
        public virtual DbSet<TBL_LINKLER> TBL_LINKLER { get; set; }
        public virtual DbSet<TBL_MESAJ> TBL_MESAJ { get; set; }
        public virtual DbSet<TBL_YONETMELIKLER> TBL_YONETMELIKLER { get; set; }
    }
}
