//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BANKABILGI
    {
        public int ID { get; set; }
        public string BANKAADI { get; set; }
        public string HESAPSAHIBI { get; set; }
        public string IBAN { get; set; }
        public string HESAPNO { get; set; }
        public string SUBEKODU { get; set; }
        public string FOTO { get; set; }
    }
}
